# Generated by Django 4.2 on 2025-04-06 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_default', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 32 characters or fewer.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$', 'Enter a valid username.', 'invalid')], verbose_name='user name'),
            preserve_default=False,
        ),
    ]
